/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfigurateurRouteImport } from './routes/configurateur'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWilayasRouteImport } from './routes/admin/wilayas'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurateurRoute = ConfigurateurRouteImport.update({
  id: '/configurateur',
  path: '/configurateur',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWilayasRoute = AdminWilayasRouteImport.update({
  id: '/wilayas',
  path: '/wilayas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commander': typeof CommanderRoute
  '/configurateur': typeof ConfigurateurRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/wilayas': typeof AdminWilayasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boutique': typeof BoutiqueRoute
  '/commander': typeof CommanderRoute
  '/configurateur': typeof ConfigurateurRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/wilayas': typeof AdminWilayasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRoute
  '/commander': typeof CommanderRoute
  '/configurateur': typeof ConfigurateurRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/wilayas': typeof AdminWilayasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/boutique'
    | '/commander'
    | '/configurateur'
    | '/login'
    | '/panier'
    | '/admin/categories'
    | '/admin/models'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/wilayas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boutique'
    | '/commander'
    | '/configurateur'
    | '/login'
    | '/panier'
    | '/admin/categories'
    | '/admin/models'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/wilayas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/boutique'
    | '/commander'
    | '/configurateur'
    | '/login'
    | '/panier'
    | '/admin/categories'
    | '/admin/models'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/wilayas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BoutiqueRoute: typeof BoutiqueRoute
  CommanderRoute: typeof CommanderRoute
  ConfigurateurRoute: typeof ConfigurateurRoute
  LoginRoute: typeof LoginRoute
  PanierRoute: typeof PanierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurateur': {
      id: '/configurateur'
      path: '/configurateur'
      fullPath: '/configurateur'
      preLoaderRoute: typeof ConfigurateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wilayas': {
      id: '/admin/wilayas'
      path: '/wilayas'
      fullPath: '/admin/wilayas'
      preLoaderRoute: typeof AdminWilayasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminWilayasRoute: typeof AdminWilayasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminWilayasRoute: AdminWilayasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BoutiqueRoute: BoutiqueRoute,
  CommanderRoute: CommanderRoute,
  ConfigurateurRoute: ConfigurateurRoute,
  LoginRoute: LoginRoute,
  PanierRoute: PanierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
